# SPDX-License-Identifier: Apache-2.0
"""Build the GEODE-RAG store over the Annual Financial Report corpus and emit a
ground-truth facts sheet (data/corpus_facts.md) the chapter authors cite.

Run:  python scripts/build_store.py
Uses the GMS-knowlytix branch library (see scripts/_bootstrap.py); override the
path with KNOWLYTIX_SRC.
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _bootstrap import KNOWLYTIX_SRC, REPO_ROOT, use_branch_library  # noqa: E402

use_branch_library()

import torch  # noqa: E402

from knowlytix.core.config import GeometryConfig, TrainConfig  # noqa: E402
from knowlytix.knowledge.config import DocGMSConfig  # noqa: E402
from knowlytix.knowledge.geode.rag import build_rag_store  # noqa: E402
from knowlytix.knowledge.geode.loop import make_default_trainer  # noqa: E402
from knowlytix.knowledge.geode.provenance import ProvenanceLedger  # noqa: E402
from knowlytix.knowledge.rag import (  # noqa: E402
    Retriever, TripleBinder, coverage_report,
)
from knowlytix.knowledge.rag.query_triples import QueryTriple  # noqa: E402

MD = os.path.join(REPO_ROOT, "data", "annual_report.md")
STORE = os.path.join(REPO_ROOT, "data", "gms_annual_report_store")
FACTS = os.path.join(REPO_ROOT, "data", "corpus_facts.md")


def main() -> None:
    dev = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    cfg = DocGMSConfig(
        store_path=STORE,
        ingest_mode="regex",
        loss_mode="cap",
        geometry=GeometryConfig(d_v=64, d_u=64, m=32, d=32),
        train=TrainConfig(epochs=150, batch_size=64, neg_samples=16,
                          lr=5e-3, lr_riemannian=2e-3),
    )
    print(f"KNOWLYTIX_SRC = {KNOWLYTIX_SRC}\nbuilding store from {MD} on {dev}")
    res = build_rag_store(MD, cfg, device=dev,
                          geode_trainer=make_default_trainer(dev, epochs=80))
    store = res.store
    print(f"\nconverged={res.converged} iters={res.iterations} "
          f"entities={res.n_entities} triples={res.n_triples} enm={res.n_enm}")
    print(f"GEODE corrections: {len(res.corrections)}  "
          f"anchor violations: {len(res.anchor_violations)}")

    _emit_facts(store)
    print(f"\nwrote {FACTS}")


def _emit_facts(store) -> None:
    ledger = ProvenanceLedger.from_text(store.markdown)
    binder = TripleBinder(store)
    retr = Retriever(store, ledger)
    L: list[str] = ["# Corpus facts — Northwind Industries FY2025",
                    "",
                    "Ground truth for chapter authors. Generated by "
                    "`scripts/build_store.py` from the trained store. Use these "
                    "exact entity/relation names and values in listings.", ""]

    rels = sorted(store.adapter.relation_to_idx)
    L += ["## Relations", "", ", ".join(f"`{r}`" for r in rels), ""]

    L += ["## Sample triples (canonicalized)", ""]
    for h, r, t in store.triples[:40]:
        if r != "in_section":
            L.append(f"- `{h}` `{r}` `{t}`")
    L.append("")

    L += ["## Exact Numerical Memory (lookup_enm category/id = value)", ""]
    if store.enm is not None:
        for key in store.enm.keys():
            val = store.enm.read_exact(key)
            v = float(val.reshape(-1)[0]) if val is not None else None
            L.append(f"- `{key.type}` / `{key.id}` = {v}")
    L.append("")

    cov = coverage_report(store)
    L += ["## Coverage (triple-mediation blind spots)", "",
          f"coverage_ratio = {cov.coverage_ratio:.2f}", ""]
    for rg in cov.regions:
        flag = "  <-- BLIND SPOT" if rg.blind_spot else ""
        L.append(f"- [{'x' if rg.covered else ' '}] {rg.title} "
                 f"({rg.triple_count} triples, {rg.body_lines} body lines){flag}")
    L.append("")

    L += ["## Sample retrieval (no LLM — Retriever over bound query triples)", ""]
    # single-hop
    bt = binder.bind(QueryTriple("cloud platform", "has_revenue", "?"))
    r1 = retr.retrieve([bt])
    L.append(f"- Q: cloud platform revenue -> "
             f"{[(f.head, f.relation, f.tail, f.location) for f in r1.facts]}")
    # two-hop: segment -> division -> region
    chain = [binder.bind(QueryTriple("cloud platform", "has_division", "?x")),
             binder.bind(QueryTriple("?x", "has_region", "?"))]
    r2 = retr.retrieve(chain)
    L.append(f"- Q: region of cloud platform's division -> "
             f"answers={r2.answers}  facts={[(f.head, f.relation, f.tail) for f in r2.facts]}")
    L.append("")

    with open(FACTS, "w", encoding="utf-8") as f:
        f.write("\n".join(L))


if __name__ == "__main__":
    main()
